version: "3"
services:
  gym:
    build: .
    restart: always
    network_mode: host
    depends_on:
      - browserless
    logging:
      options:
        max-size: 16M
    command: python GymOrder.py
  browserless:
    # See issue 6680
    image: browserless/chrome:1-chrome-stable
    restart: always
    network_mode: host
    ulimits:
      core:
        hard: 0
        soft: 0
    logging:
      options:
        max-size: 16M